"""
AES Cryptography and Key Derivation Constants.
"""

AES_ALGORITHM = "AES-256-GCM"
KEY_LENGTH_BITS = 256
KEY_LENGTH_BYTES = 32
SALT_SIZE_BYTES = 16
NONCE_SIZE_BYTES = 12
TAG_SIZE_BYTES = 16

# Key Derivation Configuration (PBKDF2-HMAC-SHA256)
PBKDF2_ITERATIONS = 100000
PBKDF2_HASH = "SHA256"

# Password Constraints
MIN_AES_PASSWORD_LENGTH = 8
MAX_AES_PASSWORD_LENGTH = 128
